"""
Compare alternative Kalman/state-space implementations on a saved test bundle.

Bundle is an .npz produced by the BM-DFM fast path (same format as the older checker):
  - each entrypoint has a dict of kwargs under key f"{fn}__kwargs"
  - expected outputs include at least: a_smooth, P_smooth, loglik (for smoother)

Implementations compared (module short names):
  - new            -> dfm_pipeline.dfm_dyn.state_space_new
  - new_cached     -> dfm_pipeline.dfm_dyn.state_space_new_cached
  - new_uni        -> dfm_pipeline.dfm_dyn.state_space_new_uni
  - new_uni_numba  -> dfm_pipeline.dfm_dyn.state_space_new_uni_numba

Typical expectation:
  - new vs new_cached: exact match (or <= 1e-15)
  - univariate variants: match up to tiny fp noise (order differs), ~1e-12..1e-14
"""

from __future__ import annotations

import argparse
import importlib
from pathlib import Path

import numpy as np


IMPL_TO_MODULE = {
    "new": "dfm_pipeline.dfm_dyn.state_space_new",
    "new_cached": "dfm_pipeline.dfm_dyn.state_space_new_cached",
    "new_uni": "dfm_pipeline.dfm_dyn.state_space_new_uni",
    "new_uni_numba": "dfm_pipeline.dfm_dyn.state_space_new_uni_numba",
}


def _load_npz_bundle(path: str) -> dict:
    d = np.load(path, allow_pickle=True)
    out = {}
    for k in d.files:
        v = d[k]
        if v.dtype == object and v.shape == ():
            out[k] = v.item()
        else:
            out[k] = v
    return out


def _max_abs(A: np.ndarray) -> float:
    return float(np.max(np.abs(A)))


def _max_abs_diff(A: np.ndarray, B: np.ndarray) -> float:
    return float(np.max(np.abs(A - B)))


def _as_dict(result):
    if hasattr(result, "__dict__"):
        return dict(result.__dict__)
    return dict(result)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--bundle",
        default="runs/cache_equiv_bundle.npz",
        help="Path to .npz bundle generated by a fast run",
    )
    ap.add_argument("--entrypoint", default="kalman_filter_smoother")
    ap.add_argument(
        "--impls",
        default="new,new_cached,new_uni,new_uni_numba",
        help="Comma-separated list of implementations to compare",
    )
    ap.add_argument("--tol", type=float, default=1e-12)
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    bundle_path = Path(args.bundle)
    if not bundle_path.exists():
        raise FileNotFoundError(f"Bundle not found: {bundle_path}")

    bundle = _load_npz_bundle(str(bundle_path))

    ep = args.entrypoint.strip()
    kwargs_key = f"{ep}__kwargs"
    if kwargs_key not in bundle:
        raise KeyError(f"Missing key in bundle: {kwargs_key}")

    kwargs = bundle[kwargs_key]
    if not isinstance(kwargs, dict):
        raise TypeError(f"{kwargs_key} must be a dict, got {type(kwargs)}")

    impls = [x.strip() for x in args.impls.split(",") if x.strip()]
    mods = []
    for impl in impls:
        if impl not in IMPL_TO_MODULE:
            raise ValueError(f"Unknown impl: {impl}. Known: {sorted(IMPL_TO_MODULE)}")
        mods.append((impl, importlib.import_module(IMPL_TO_MODULE[impl])))

    results = []
    for impl, mod in mods:
        fn = getattr(mod, ep, None)
        if fn is None:
            raise AttributeError(f"{IMPL_TO_MODULE[impl]} has no {ep}()")

        res = fn(**kwargs)
        resd = _as_dict(res)

        keep = {}
        for k in ("a_smooth", "P_smooth", "a_filt", "P_filt", "a_pred", "P_pred", "loglik"):
            if k in resd:
                keep[k] = resd[k]
        results.append((impl, keep))

    ref_impl, ref = results[0]
    print(f"REFERENCE: {ref_impl}")
    for impl, out in results[1:]:
        diffs = {}
        for k, v in out.items():
            if k == "loglik":
                diffs[k] = float(abs(ref["loglik"] - v))
            else:
                diffs[k] = _max_abs_diff(ref[k], v)

        ok = all(d <= args.tol for d in diffs.values())
        status = "OK" if ok else "DIFF"
        diffs_str = " ".join([f"{k}={d:.3e}" for k, d in diffs.items()])
        print(f"{status}: {impl} vs {ref_impl}: {diffs_str}")

        if args.verbose and not ok:
            for k, d in diffs.items():
                if k == "loglik":
                    print(f"  {k}: ref={ref['loglik']:.3e} diff={d:.3e}")
                else:
                    print(f"  {k}: max_abs_ref={_max_abs(ref[k]):.3e} max_abs_diff={d:.3e}")

    print("NOTE: univariate variants may differ by tiny fp noise vs multivariate.")


if __name__ == "__main__":
    raise SystemExit(main())
